# This is an example configuration for PocketDisco under Linux.
# Rename this file to 'config.yaml' to use this configuration.

!<PocketDiscoConfiguration>
# Port of the Flask web server
port: 5000

# Logging level
# 10 == logging.DEBUG
# 20 == logging.INFO
# 30 == logging.WARNING
# 40 == logging.ERROR
# 50 == logging.CRITICAL
log_level: 10

# For every -!<stream> entry a stream with the given properties will be generated.
# Missing properties will be filled with defaults.
# The following properties are available:
# name: Name of the stream for identification.
# rate: the sampling rate of the portaudio stream in Hz. Default: 44100
# device: the audio device to be used by portaudio. Use "pulse" for pulseaudio support with ALSA.
# channels: Number of channels to be sampled. Default: 2
#           NOTE: Under Linux you should probably leave this at 2 at the moment.
# max_segments: Maximum number of segments to be buffered for the stream. Default: 5
# segment_duration: Segment length in seconds. Default: 5
# format: paInt16 | paInt24 | paInt32 | paFloat32 -> The sampling format to be used. Default: paInt16
streams:
- !<stream>
  name: stream_name
  rate: 44100
  device: pulse
  channels: 2
  max_segments: 5
  format: paInt16
- !<stream>
  name: stream_name2
  rate: 44100
  device: pulse
  channels: 2
  max_segments: 5
  format: paInt16
- !<stream>
  name: stream_name3
  rate: 44100
  device: pulse
  channels: 2
  max_segments: 5
  format: paInt16

# If this is set to true PocketDisco will create loopback null-sink-sources and attach the the input streams to them.
# NOTE: Currently this will only work if all your streams use pulseaudio!
use_pulseaudio: true
